- name: Configure master server
  lineinfile:
    state: present
    backrefs: yes
    dest: "{{ pgsqlrep_data_path[pgsql_major_version] }}/postgresql.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ pgsqlrep_postgres_conf_lines }}"
  notify: restart postgresql

- name: Verify replication user account
  shell:  'psql -Xc \\du | grep "{{ pgsqlrep_user }}"'
  environment:
    PATH: /opt/rh/rh-postgresql10/root/usr/bin:{{ ansible_env.PATH }}
    LIBRARY_PATH: /opt/rh/rh-postgresql10/root/usr/lib64
    JAVACONFDIRS: '/etc/opt/rh/rh-postgresql10/java:/etc/java'
    LD_LIBRARY_PATH: /opt/rh/rh-postgresql10/root/usr/lib64
    CPATH: /opt/rh/rh-postgresql10/root/usr/include
    PKG_CONFIG_PATH: /opt/rh/rh-postgresql10/root/usr/lib64/pkgconfig
  become: yes
  become_user: postgres
  ignore_errors: yes
  register: useraccount_status

- name: Create replication user account
  command: psql -c "CREATE USER {{ pgsqlrep_user }} REPLICATION LOGIN ENCRYPTED PASSWORD '{{ pgsqlrep_password }}';"
  environment:
    PATH: /opt/rh/rh-postgresql10/root/usr/bin:{{ ansible_env.PATH }}
    LIBRARY_PATH: /opt/rh/rh-postgresql10/root/usr/lib64
    JAVACONFDIRS: '/etc/opt/rh/rh-postgresql10/java:/etc/java'
    LD_LIBRARY_PATH: /opt/rh/rh-postgresql10/root/usr/lib64
    CPATH: /opt/rh/rh-postgresql10/root/usr/include
    PKG_CONFIG_PATH: /opt/rh/rh-postgresql10/root/usr/lib64/pkgconfig
  become: yes
  become_user: postgres
  when: useraccount_status.rc != 0

- name: Add trust in pg_hba.conf
  lineinfile:
    state: present
    dest: "{{ pgsqlrep_data_path[pgsql_major_version] }}/pg_hba.conf"
    regexp: 'host.*replication.*{{ item }}/32.*trust'
    line: 'host    replication    {{ pgsqlrep_user }}  {{ item }}/32 trust'
  loop: "{{ pgsqlrep_replica_address }}"
  notify: restart postgresql
