---

- name: tower service stop block
  become: true
  block:
  
  - wait_for_connection:
      timeout: 10
    register: tower_available
    ignore_errors: yes

  - name: Stop tower
    command: ansible-tower-service stop
    when: not tower_available.failed
    ignore_errors: yes